[build]
  command = "npm install"  # Your build command
  publish = "templates"           # The directory to publish (adjust based on your build output)

[dev]
  command = "node index.js"  # Command for local development
  port = 3000            # Port for local development server

[[redirects]]
  from = "/old-url/*"
  to = "/new-url/:splat"
  status = 301
  force = true

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
